Q1: Write a python program to scrape data for “Data Analyst” Job position in 
“Bangalore” location. You have to scrape the job-title, job-location, company_name,
experience_required. You have to scrape first 10 jobs data.

This task will be done in following steps:
1. first get the webpage https://www.naukri.com/
2. Enter “Data Analyst” in “Skill,Designations,Companies” field and enter “Bangalore” 
in “enter the location” field.
3. Then click the search button.
4. Then scrape the data for the first 10 jobs results you get.
5. Finally create a dataframe of the scraped data.
Note- All of the above steps have to be done in code. No step is to be done manually.

In [14]:
import selenium
import pandas as pd
from selenium import webdriver
import time

In [15]:
driver=webdriver.Chrome(r'chromedriver.exe')
driver

In [16]:
url="https://www.naukri.com/"
driver.get(url)

In [19]:
search_job_title=driver.find_element_by_id("qsb-keyword-sugg")
search_job_title.send_keys("Data Analyst")

In [20]:
search_job_location=driver.find_element_by_id("qsb-location-sugg")
search_job_location.send_keys("Bangalore")

In [26]:
search_button=driver.find_element_by_xpath("//button[@class='btn']")
search_button.click()

In [27]:
titles=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
titles

[<selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="c8803e50-5a87-4d18-be63-87483f8e630f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="5dda8c18-a11d-40bc-9f1c-c529cea32785")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="2fd73112-a153-45ff-963e-0a8e3ebd79f5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="e12349cb-c0a5-4db5-868f-7391eedb3ec2")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="f486b530-8963-4135-b68e-68006742693b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="727a4303-25c2-4c2d-847c-fd9a9c8a4821")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="05f868ed-49d5-4b2c-b27e-cbb301d52630")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="209effa5-46ce-412b-afc4-cef31c7ce934")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="c9e24076-5501-4c91-8190-b18af3725e11")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="a649a649-3456-42b7-aec4-c56009bd9bff")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="3f27f2f9-20f2-49e4-b15b-9429d06c3601")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="cbcb2394-225b-4fc4-bfac-4de40b2375a8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="83c26c02-3489-4d4e-9bd7-16672fe4779c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="87e51079-5820-4f45-bcfe-f56d041e69bd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="d05460f5-46a5-429f-9677-de7c0e922563")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="fe785b0f-4dc2-4ae0-be8b-023f4c08c33e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="28ee75ad-901e-4191-a70a-9fac8f8a3f82")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="6d41b5ae-308d-43fa-8531-ab76436cbbaa")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="019663ab-d8ea-496e-9e58-d07ef739bad3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="309166ed-bfb0-4995-b442-8486c1bbff49")>]

In [28]:
title=[]
for i in titles:
    title.append(i.text)
title

['Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst - Informatica MDM',
 'Data Analyst - Graphy',
 'Concentrix Innovation Labs is Hiring For Big Data- Data Analyst',
 'Data Analyst',
 'Hiring For Data Analyst/ MIS Reporting Analyst - Bangalore',
 'Data Analyst',
 'Assistant Vice President - MIS & Reporting ( Business Data Analyst)',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Data Analyst',
 'Sr Data Operations Analyst',
 'Data Analyst',
 'Data Business Analyst - Module Lead/ Technical Lead',
 'Analyst Data Science Analytics',
 'Supply Data Analyst']

In [29]:
companies=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
companies

[<selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="e9542d30-a2b5-49f9-a633-fa28554c1eed")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="7f4b137c-bb84-4534-baa7-befd64399a77")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="2b90a3c6-caf3-4e7e-abb3-7b8bf01ec979")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="54d98858-c8d4-4d93-99ec-f32f8f690c6a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="67e1a78a-e04c-4a29-937b-ba07e4ceb6e3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="e2295b29-1a3b-43db-811a-d1e2420da24b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="f0beeda0-042e-453d-8e68-5457fc704b0e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="b1395280-9a28-4792-9be6-f85dda36e33d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="5588ad4b-5ad6-44a9-8a75-2db210fd4ab7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="4b7df2e3-35be-4e8c-9f82-0a7584f51383")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="7f7aa4e0-1ee6-4165-9732-b5b6bf517cdb")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="8838af7b-5694-4fd4-add0-d2da616eb04f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="4b0aea5e-80fd-4380-ae0c-ab1279446243")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="07d5510d-0426-4dea-964a-34de50062784")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="e96a4aa5-5bcf-499d-9def-9aa3b08e975b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="8f23204b-884a-4225-b825-6f4ec64db023")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="c9efaa9e-a73e-4c69-a866-b3773e82b5a0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="9d03ed75-aa54-4df8-a76f-bad7a545d74c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="6b3271ee-af95-4e49-8553-2bf921046892")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="3f1c8585-0da4-49ab-a942-72af185072e0")>]

In [30]:
company=[]
for i in companies:
    company.append(i.text)
company

['Shell India Markets Private Limited',
 'Applied Materials',
 'Liventus, Inc.',
 'Kwalee ltd.',
 'Shell India Markets Private Limited',
 'Unacademy',
 'Concentrix Daksh Services India Private Limited.',
 'SA Tech Software (I) Pvt. Ltd.',
 'PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd',
 'Concerto.ai',
 'INTERTRUSTVITEOS CORPORATE AND FUND SERVICES PVT. LTD.',
 'Myntra Designs Pvt. Ltd.',
 'Myntra Designs Pvt. Ltd.',
 'Myntra Designs Pvt. Ltd.',
 'Myntra Designs Pvt. Ltd.',
 'Silicon Valley Bank',
 'Myntra Designs Pvt. Ltd.',
 'Mindtree Limited',
 'Empower Retirement',
 'GLOBALFOUNDRIES Engineering Private Limited']

In [31]:
experiences=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi experience']")
experiences

[<selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="896b3b79-cf3a-43b5-9b55-bf5c59485a52")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="ecd39410-7690-4b69-a52d-c63dbbad85f3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="ff6189bf-53a1-4995-a9d3-781d7928e6e9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="7f2020ce-1653-4fc0-aa78-bf4ef380acca")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="e1e72f82-f476-4ccc-8786-f8c0dd34ac92")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="d181301c-ca83-4dba-a392-6776ecccc7e9")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="74a6db25-e4a4-4179-b4d2-b91f9dee5c1a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="40709c27-348f-4d85-939c-227f55d9cd08")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="37e26ea3-66dc-4526-b0c9-deed9c13966a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="268c0a01-ffe7-412a-af51-69f060b2c468")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="205e7270-f4ab-4f77-81ba-c8ea29f19443")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="0fd0cdde-369f-4578-9306-d74b4966943d")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="521ba1a0-a676-4750-9363-161f7b55bb65")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="3a088ea5-02cc-4e90-88a6-fd5cf4e8c71c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="4f6f8f38-4fff-4336-8f2f-9338b653468f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="0288a63e-22a1-47c2-8d4e-4cd64875e144")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="928c51d9-1bbc-4bca-9796-8ca9c4b185cc")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="f7ef257e-a695-4ba0-9a91-a3f914efe681")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="b9942def-ad52-447b-a2a6-2d93e851c78a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="7e50029a-8ace-4c87-92ca-5c1e774acc58")>]

In [32]:
experience=[]
for i in experiences:
    experience.append(i.text)
experience

['5-8 Yrs',
 '7-10 Yrs',
 '3-6 Yrs',
 '2-7 Yrs',
 '6-9 Yrs',
 '1-4 Yrs',
 '2-7 Yrs',
 '1-3 Yrs',
 '2-4 Yrs',
 '3-5 Yrs',
 '12-18 Yrs',
 '3-6 Yrs',
 '3-6 Yrs',
 '4-9 Yrs',
 '4-8 Yrs',
 '3-6 Yrs',
 '3-6 Yrs',
 '5-8 Yrs',
 '2-6 Yrs',
 '2-5 Yrs']

In [33]:
locations=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']")
locations

[<selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="3bcef96e-8153-4f25-a238-2710a15e517a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="c6967ce1-4b21-44e4-b117-9fbccfc30266")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="0175fa89-1ce4-40d7-a40b-8251e0d43b5f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="344f7e2d-d061-4038-b6ab-bfcaf83edd04")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="ed1977ee-e25d-4c3e-bb90-d2131253b9f3")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="a68dfaf5-bb0e-4d6d-81e3-e0c6336ed5d5")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="cd20a9a2-6cbe-415a-bcd4-0d9e07d3ea41")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="c1a9f1f2-1b46-48e2-b01a-fce3b2f615cd")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="c328202a-124e-4c0a-93ee-249f4a35976f")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="b3e5a85e-16a5-4541-8590-8c21a523cd7a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="d3625139-e225-42ed-8e9f-c9da4b21307a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="ac2a8d18-6997-4284-9d2d-ad5a13413e41")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="338ff9b0-be56-40d5-b3f5-ee3119152ad8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="b8374dbe-aa78-48a1-b863-f01c1d9f5afe")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="1e5bdaaa-554f-444d-9e9b-da8850e6185a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="603a7c66-64de-42a7-866c-add42d6455ce")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="146b1856-31af-4ba5-a970-4b6a55a29cce")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="1d2fe1f9-a736-4e5d-b694-66f886480769")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="5fe6fb1d-1ff7-4056-96b8-a29853e76181")>,
 <selenium.webdriver.remote.webelement.WebElement (session="16d69c62748b72e5aa47ca42734d57b0", element="317aab84-82c7-404e-9d27-aefaa9dff2f0")>]

In [34]:
location=[]
for i in locations:
    location.append(i.text)
location

['Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru(2nd Phase JP Nagar)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru, Delhi / NCR',
 'Kolkata, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR, Mumbai (All Areas)',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Mumbai, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru, Remote',
 'Bangalore/Bengaluru']

In [39]:
df=pd.DataFrame({})
df['Title']=title
df['Company']=company
df['Experience,(in yrs)']=experience
df['Location']=location
df

,Title,Company,"Experience,(in yrs)",Location
0,Data Analyst,Shell India Markets Private Limited,5-8 Yrs,Bangalore/Bengaluru
1,Data Analyst,Applied Materials,7-10 Yrs,Bangalore/Bengaluru
2,Data Analyst,"Liventus, Inc.",3-6 Yrs,Bangalore/Bengaluru(2nd Phase JP Nagar)
3,Data Analyst,Kwalee ltd.,2-7 Yrs,Bangalore/Bengaluru
4,Data Analyst - Informatica MDM,Shell India Markets Private Limited,6-9 Yrs,Bangalore/Bengaluru
5,Data Analyst - Graphy,Unacademy,1-4 Yrs,Bangalore/Bengaluru
6,Concentrix Innovation Labs is Hiring For Big D...,Concentrix Daksh Services India Private Limited.,2-7 Yrs,"Bangalore/Bengaluru, Delhi / NCR"
7,Data Analyst,SA Tech Software (I) Pvt. Ltd.,1-3 Yrs,"Kolkata, Pune, Chennai, Bangalore/Bengaluru, D..."
8,Hiring For Data Analyst/ MIS Reporting Analyst...,PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd,2-4 Yrs,Bangalore/Bengaluru
9,Data Analyst,Concerto.ai,3-5 Yrs,Bangalore/Bengaluru
10,Assistant Vice President - MIS & Reporting ( B...,INTERTRUSTVITEOS CORPORATE AND FUND SERVICES P...,12-18 Yrs,"Mumbai, Bangalore/Bengaluru"
11,Data Analyst,Myntra Designs Pvt. Ltd.,3-6 Yrs,Bangalore/Bengaluru
12,Data Analyst,Myntra Designs Pvt. Ltd.,3-6 Yrs,Bangalore/Bengaluru
13,Data Analyst,Myntra Designs Pvt. Ltd.,4-9 Yrs,Bangalore/Bengaluru
14,Data Analyst,Myntra Designs Pvt. Ltd.,4-8 Yrs,Bangalore/Bengaluru
15,Sr Data Operations Analyst,Silicon Valley Bank,3-6 Yrs,Bangalore/Bengaluru
16,Data Analyst,Myntra Designs Pvt. Ltd.,3-6 Yrs,Bangalore/Bengaluru
17,Data Business Analyst - Module Lead/ Technical...,Mindtree Limited,5-8 Yrs,Bangalore/Bengaluru
18,Analyst Data Science Analytics,Empower Retirement,2-6 Yrs,"Bangalore/Bengaluru, Remote"
19,Supply Data Analyst,GLOBALFOUNDRIES Engineering Private Limited,2-5 Yrs,Bangalore/Bengaluru

In [40]:
df=df.head(10)
df

,Title,Company,"Experience,(in yrs)",Location
0,Data Analyst,Shell India Markets Private Limited,5-8 Yrs,Bangalore/Bengaluru
1,Data Analyst,Applied Materials,7-10 Yrs,Bangalore/Bengaluru
2,Data Analyst,"Liventus, Inc.",3-6 Yrs,Bangalore/Bengaluru(2nd Phase JP Nagar)
3,Data Analyst,Kwalee ltd.,2-7 Yrs,Bangalore/Bengaluru
4,Data Analyst - Informatica MDM,Shell India Markets Private Limited,6-9 Yrs,Bangalore/Bengaluru
5,Data Analyst - Graphy,Unacademy,1-4 Yrs,Bangalore/Bengaluru
6,Concentrix Innovation Labs is Hiring For Big D...,Concentrix Daksh Services India Private Limited.,2-7 Yrs,"Bangalore/Bengaluru, Delhi / NCR"
7,Data Analyst,SA Tech Software (I) Pvt. Ltd.,1-3 Yrs,"Kolkata, Pune, Chennai, Bangalore/Bengaluru, D..."
8,Hiring For Data Analyst/ MIS Reporting Analyst...,PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd,2-4 Yrs,Bangalore/Bengaluru
9,Data Analyst,Concerto.ai,3-5 Yrs,Bangalore/Bengaluru

In [43]:
df['Experience,(in yrs)']=df['Experience,(in yrs)'].apply(lambda x:x[0:-4])

<ipython-input-43-037b99e938cd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Experience,(in yrs)']=df['Experience,(in yrs)'].apply(lambda x:x[0:-4])

In [44]:
df

,Title,Company,"Experience,(in yrs)",Location
0,Data Analyst,Shell India Markets Private Limited,5-8,Bangalore/Bengaluru
1,Data Analyst,Applied Materials,7-10,Bangalore/Bengaluru
2,Data Analyst,"Liventus, Inc.",3-6,Bangalore/Bengaluru(2nd Phase JP Nagar)
3,Data Analyst,Kwalee ltd.,2-7,Bangalore/Bengaluru
4,Data Analyst - Informatica MDM,Shell India Markets Private Limited,6-9,Bangalore/Bengaluru
5,Data Analyst - Graphy,Unacademy,1-4,Bangalore/Bengaluru
6,Concentrix Innovation Labs is Hiring For Big D...,Concentrix Daksh Services India Private Limited.,2-7,"Bangalore/Bengaluru, Delhi / NCR"
7,Data Analyst,SA Tech Software (I) Pvt. Ltd.,1-3,"Kolkata, Pune, Chennai, Bangalore/Bengaluru, D..."
8,Hiring For Data Analyst/ MIS Reporting Analyst...,PHARMACEUTICAL RESEARCH ASSOCIATES INDIA Pvt Ltd,2-4,Bangalore/Bengaluru
9,Data Analyst,Concerto.ai,3-5,Bangalore/Bengaluru

Q2: Write a python program to scrape data for “Data Scientist” Job position in
“Bangalore” location. You have to scrape the job-title, job-location,
company_name, full job-description. You have to scrape first 10 jobs data.
This task will be done in following steps:
1. first get the webpage https://www.naukri.com/
2. Enter “Data Scientist” in “Skill,Designations,Companies” field and enter
“Bangalore” in “enter the location” field.
3. Then click the search button.
4. Then scrape the data for the first 10 jobs results you get.
5. Finally create a dataframe of the scraped data.

In [28]:
import selenium
import pandas as pd
import time
from selenium import webdriver

In [29]:
driver=webdriver.Chrome(r"chromedriver.exe")
driver.get("https://www.naukri.com/")

In [30]:
designation_search=driver.find_element_by_id("qsb-keyword-sugg")
designation_search.send_keys("Data Scientist")
location_search=driver.find_element_by_id("qsb-location-sugg")
location_search.send_keys("Bangalore")
search_btn=driver.find_element_by_xpath("//div[@class='search-btn']")
time.sleep(4)
search_btn.click()

In [31]:
job_titles=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
title=[]
for i in job_titles:
    title.append(i.text)
title

['Data Scientist / Data Analyst -Business Analyst',
 'Senior Data Scientist | CES IT LTD | CMMI Level 5',
 'Senior Data Scientist | CES IT LTD | CMMI Level 5',
 'Analytics & AI Product Mgmt - Sr. Data Scientist',
 'Senior Data Scientist',
 'Senior Data Scientist, Modeling',
 'Data Scientist - IBM Garage',
 'Data Scientist',
 'Data Scientist',
 'Senior Data Scientist - Credit risk',
 'SDE Lead Data Scientist-L3',
 'Computational Design Lead Data Scientist-L3',
 'Data Scientist',
 'Lead Data Scientist',
 'Senior Data Scientist - Chatbot & NLP',
 'Senior Data Scientist - Chatbot & NLP',
 'Senior Data Scientist',
 'Senior Data Scientist - Kinara Capital',
 'Senior Data Scientist',
 'Data Scientist']

In [32]:
companies=driver.find_elements_by_xpath("//a[@class='subTitle ellipsis fleft']")
company=[]
for i in companies:
    company.append(i.text)
company

['Inflexion Analytix Private Limited',
 'CES Ltd.',
 'CES Ltd.',
 'GlaxoSmithKline Pharmaceuticals Limited',
 'Vijaya Management Services',
 'Nielsen',
 'IBM India Pvt. Limited',
 'IBM India Pvt. Limited',
 'IBM India Pvt. Limited',
 'Scienaptic Systems',
 'Huawei Technologies India Pvt Ltd',
 'Huawei Technologies India Pvt Ltd',
 'IBM India Pvt. Limited',
 'Intel Technology India Pvt Ltd',
 'Gojek Tech',
 'GO-JEK India',
 'Kinara Financial Private Limited',
 'Kinara Financial Private Limited',
 'Superior Group',
 'Applied Materials']

In [33]:
job_locations=driver.find_elements_by_xpath("//li[@class='fleft grey-text br2 placeHolderLi location']")
location=[]
for i in job_locations:
    location.append(i.text)
location

['Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/Gurugram, Chennai, Bangalore/Bengaluru',
 'Kolkata, Mumbai, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR',
 'Kolkata, Mumbai, Hyderabad/Secunderabad, Pune, Chennai, Bangalore/Bengaluru, Delhi / NCR',
 'Bangalore/Bengaluru',
 'Pune, Chennai, Bangalore/Bengaluru',
 'Kolkata, Gurgaon/Gurugram, Bangalore/Bengaluru, Vadodara, Mumbai (All Areas)',
 'Noida, Hyderabad/Secunderabad, Bangalore/Bengaluru',
 'Noida, Hyderabad/Secunderabad, Bangalore/Bengaluru',
 'Noida, Hyderabad/Secunderabad, Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru',
 'Bangalore/Bengaluru']

In [34]:
job_descriptions=driver.find_elements_by_xpath("//div[@class='job-description fs12 grey-text']")
job_description=[]
for i in job_descriptions:
    job_description.append(i.text)
job_description

['Applications invited from all Freshers and experienced candidates (0-3 yrs) aspiring to...',
 'Must be extremely detail and technology-oriented and possess excellent communications s...',
 'Must be extremely detail and technology-oriented and possess excellent communications s...',
 'A higher degree (PhD preferred) in Engineering, Statistics, Data Science, Applied Mathe...',
 '3+ years practical experience with advanced machine learning techniques and big data te...',
 'Masters degree in Economics, Mathematics, Statistics, Engineering 5 years of relevant e...',
 'Required Technical and Professional ExpertisePreferred Technical and Professional Exper...',
 'Should have hired and nurtured talent and grow them in market facing specialists and co...',
 'Should have hired and nurtured talent and grow them in market facing specialists and co...',
 'Responsibilities and duties Focus on developing clear and concise analytical approach f...',
 'Strong hands-on experience in implementing and validating big data algorithms and model...',
 'Business & Team overview:Founded in 1987, Huawei is a leading global provider of ICT (i...',
 'modeling and business system design with experience in relational SQL and NoSQL databas...',
 'Experience in using data analysis techniques and ML methods like classification, regres...',
 'Solid knowledge of Data Science and Machine Learning fundamentals, with proven experien...',
 'Solid knowledge of Data Science and Machine Learning fundamentals, with proven experien...',
 'Qualification: Any graduate in You should be a deeply curious person with a lot of humi...',
 'You should be a deeply curious person with a lot of humility and aptitude in Math and S...',
 'Industry experience as a Data Scientist and experience in machine learning, data mining...',
 'Education: Bachelors Degree analyzes possible solutions using technical experience and ...']

In [35]:
df=pd.DataFrame({})
df['Job_Title']=title
df['Job_Location']=location
df['Company']=company
df['Job Description']=job_description
df

,Job_Title,Job_Location,Company,Job Description
0,Data Scientist / Data Analyst -Business Analyst,"Mumbai, Hyderabad/Secunderabad, Pune, Gurgaon/...",Inflexion Analytix Private Limited,Applications invited from all Freshers and exp...
1,Senior Data Scientist | CES IT LTD | CMMI Level 5,"Kolkata, Mumbai, Hyderabad/Secunderabad, Pune,...",CES Ltd.,Must be extremely detail and technology-orient...
2,Senior Data Scientist | CES IT LTD | CMMI Level 5,"Kolkata, Mumbai, Hyderabad/Secunderabad, Pune,...",CES Ltd.,Must be extremely detail and technology-orient...
3,Analytics & AI Product Mgmt - Sr. Data Scientist,Bangalore/Bengaluru,GlaxoSmithKline Pharmaceuticals Limited,A higher degree (PhD preferred) in Engineering...
4,Senior Data Scientist,"Pune, Chennai, Bangalore/Bengaluru",Vijaya Management Services,3+ years practical experience with advanced ma...
5,"Senior Data Scientist, Modeling","Kolkata, Gurgaon/Gurugram, Bangalore/Bengaluru...",Nielsen,"Masters degree in Economics, Mathematics, Stat..."
6,Data Scientist - IBM Garage,"Noida, Hyderabad/Secunderabad, Bangalore/Benga...",IBM India Pvt. Limited,Required Technical and Professional ExpertiseP...
7,Data Scientist,"Noida, Hyderabad/Secunderabad, Bangalore/Benga...",IBM India Pvt. Limited,Should have hired and nurtured talent and grow...
8,Data Scientist,"Noida, Hyderabad/Secunderabad, Bangalore/Benga...",IBM India Pvt. Limited,Should have hired and nurtured talent and grow...
9,Senior Data Scientist - Credit risk,Bangalore/Bengaluru,Scienaptic Systems,Responsibilities and duties Focus on developin...
10,SDE Lead Data Scientist-L3,Bangalore/Bengaluru,Huawei Technologies India Pvt Ltd,Strong hands-on experience in implementing and...
11,Computational Design Lead Data Scientist-L3,Bangalore/Bengaluru,Huawei Technologies India Pvt Ltd,"Business & Team overview:Founded in 1987, Huaw..."
12,Data Scientist,Bangalore/Bengaluru,IBM India Pvt. Limited,modeling and business system design with exper...
13,Lead Data Scientist,Bangalore/Bengaluru,Intel Technology India Pvt Ltd,Experience in using data analysis techniques a...
14,Senior Data Scientist - Chatbot & NLP,Bangalore/Bengaluru,Gojek Tech,Solid knowledge of Data Science and Machine Le...
15,Senior Data Scientist - Chatbot & NLP,Bangalore/Bengaluru,GO-JEK India,Solid knowledge of Data Science and Machine Le...
16,Senior Data Scientist,Bangalore/Bengaluru,Kinara Financial Private Limited,Qualification: Any graduate in You should be a...
17,Senior Data Scientist - Kinara Capital,Bangalore/Bengaluru,Kinara Financial Private Limited,You should be a deeply curious person with a l...
18,Senior Data Scientist,Bangalore/Bengaluru,Superior Group,Industry experience as a Data Scientist and ex...
19,Data Scientist,Bangalore/Bengaluru,Applied Materials,Education: Bachelors Degree analyzes possible ...

In [36]:
des=driver.find_elements_by_xpath("//a[@class='title fw500 ellipsis']")
des

[<selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="809678fa-8a96-4cfe-8447-7c7b937f3e12")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="39b13c8e-06cf-4cfe-b56a-57756cd398e8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="1dd777aa-fb7a-4bb1-b380-f5f2342b482b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="0b8cca47-2fcf-47ba-9201-b86313b5d17b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="90654754-a6ea-45df-8ff4-7c16379cc9d0")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="b36b5808-a3ba-4721-aa5c-f79d2e177732")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="0395d1b7-a20f-47c8-b7f9-e372a771cc37")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="5c6cb0a2-94fd-4439-a345-80cf1b8ce0f7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="6550e1ba-1929-47a6-a10c-d973e867274c")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="a90a792e-0711-4da4-b920-379aeff99332")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="bb1b823b-aa18-490c-afe6-53fd582a40f7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="99e6e786-bb44-48ad-aca9-d5b499d2891e")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="fc807b10-0170-49db-a93f-81348df45dc8")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="7185f8f6-baa6-4046-8440-6cc1a7e40414")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="50ab457f-2707-400d-be32-5754747a978a")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="9796c644-2709-45c0-b518-eeca627b33ef")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="cc8e35d7-94d1-41f4-afe7-bab9bf3ba8a7")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="02ed1258-da8f-4724-b953-6be850b0874b")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="c8cf7120-53b9-4ed2-8ce9-c09881b2c860")>,
 <selenium.webdriver.remote.webelement.WebElement (session="e422ef56a2f164f696851c289f06b45b", element="b77c77d0-7c6b-457b-a21c-514700b5b978")>]

'Data Scientist / Data Analyst -Business Analyst'

In [37]:
des[0].click()

In [40]:
driver.current_url

'https://www.naukri.com/data-scientist-jobs-in-bangalore?k=data%20scientist&l=bangalore'

In [39]:
de=driver.find_element_by_xpath("//div[@class='dang-inner-html']")
de.click()

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//div[@class='dang-inner-html']"}
  (Session info: chrome=90.0.4430.212)

Q-3